# Generated by Django 5.1.3 on 2024-12-04 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_remove_conversation_user_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Участник обсуждения', 'verbose_name_plural': 'Участники обсуждения'},
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='name', max_length=1024, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_set', to='films.group'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to='films.group'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
